### ISSUE TITLE
mochijson2, reloader are in mochiweb and shouldn't be separately maintained

### ISSUE THREAD

**Issue by etrepum** [agner/agner#118]
It's a good idea to have mochijson2 and reloader separately in agner for discoverability, but it's bad because these are not officially maintained forks and will cause code clashes (maybe even with different code) if mochiweb is also used.

Some possible workarounds:
- Remove them
- Have them use the code from mochiweb directly in some manner

**Comment by yrashk** [comment]
- Moved them to the limbo
- Will rewrite them to cut the modules out dynamically

**Comment by yrashk** [comment]
reloader is cutting out necessary parts out of mochiweb dynamically

**Comment by nox** [comment]
I'm strongly against their removal and think we should have them in separate packages. Maybe we should try convincing mochi guys to separate them themselves. Why they are bundled together baffles me.

**Comment by yrashk** [comment]
nox, I already rewrote reloader package to fetch mochiweb and then cut everything unnecessary out. I am going to do the same to mochijson2

**Comment by etrepum** [comment]
@nox - when mochiweb was written in 2007, years before rebar existed, it was very difficult to have Erlang packages that depended on other Erlang packages in a sensible way.

**Comment by yrashk** [comment]
mochijson2 package is cutting out necessary parts out of mochiweb dynamically now

**Comment by nox** [comment]
@etrepum - and as you said, things have changed since this time.

**Comment by etrepum** [comment]
@nox if I had infinite time to spent maintaining open source software, and I didn't have to worry about compatibility with our proprietary code base, or if there was a practical benefit to us to split it up, then maybe it'd have happened by now. As it stands, there is actually nothing for us to gain (internally,anyway) by splitting up mochiweb into several packages, it will only slow things down.

**Comment by yrashk** [comment]
@nox we can deal with this ourselves (as we already do), as it is apparently too much of a hassle for mochi. not a big deal. all I care about is a benefit for the community

**Comment by yrashk** [comment]
@etrepum, as per your suggestion on IRC I have renamed mochijson2 package to mochijson and included mochijson.erl

**Comment by yrashk** [comment]
Closing this issue. @etrepum, please let us know if you will decide to split those modules out in your own packages.
