### ISSUE TITLE
Oneliner crashes on Mac OS X

### ISSUE THREAD

**Issue by mcandre** [agner/agner#147]
Specs:

Erlang R14B01
MacPorts 1.9.2
Mac OS X 10.6.6

Trace:

```
$ curl https://github.com/agner/agner/raw/master/scripts/oneliner | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
147   295  147   295    0     0     98      0  0:00:03  0:00:03 --:--:-- 11346
Cloning into /tmp/agner.Pped8U...
remote: Counting objects: 1566, done.
remote: Compressing objects: 100% (863/863), done.
remote: Total 1566 (delta 1107), reused 982 (delta 697)
Receiving objects: 100% (1566/1566), 3.71 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (1107/1107), done.
Uncaught error in rebar_core: {'EXIT',
                                  {undef,
                                      [{crypto,start,[]},
                                       {rebar,run_aux,1},
                                       {rebar,main,1},
                                       {escript,run,2},
                                       {escript,start,1},
                                       {init,start_it,1},
                                       {init,start_em,1}]}}
make: *** [deps] Error 1
```

That's a pity; I desperately want a package manager to handle getopt, Triq, and other dependencies for my projects.

**Comment by ferd** [comment]
Sounds like you don't have the crypto stuff installed. Compiling Erlang with crypto support should solve your problem

**Comment by yrashk** [comment]
It's not even agner's exception, it's rebar failing. But yes, crypto is a must.

**Comment by yrashk** [comment]
@mcandre, please let us know if this helped.

**Comment by mcandre** [comment]
That was quick! Yes, it turned out crypto was not installed. The solution was to run "sudo port install erlang +ssl", then redo the oneliner installation.

Also, I didn't know that I had to use "sudo agner install SOMEPACKAGE", but I did to get triq and getopt.

**Comment by yrashk** [comment]
@mcandre, installation is not the best way as it poses many potential inconsistency risks (different versions used by different apps). I woud personally recomend to use agner build command, or better yet our new rebar integration (read at the bottom of the README.md file)
