### ISSUE TITLE
Undocumented: how do I import an agner-obtained library?

### ISSUE THREAD

**Issue by mcandre** [agner/agner#148]
This code gives me an error

```
import(getopt).

exception error: undefined function getopt:usage/2
```

So I tried

```
-include_lib("getopt/include/getopt.hrl").

can't find include lib "getopt/include/getopt.hrl"
```

Agner installed correctly. Getopt installed correctly. How do I import getopt in my Erlang code?

**Comment by yrashk** [comment]
If you used install, make sure your ERL_LIBS os env variable points to /usr/local/agner/packages

for example

```
 $ ERL_LIBS=/usr/local/agner/packages erl
```

Please let me know if this helped

**Comment by yrashk** [comment]
(also, it is `-import`, not `import`)

**Comment by mcandre** [comment]
Thanks! In the future, could the agner installer try to add /usr/local/agner/packages to ERL_LIBS in ~/.profile for Mac users?

**Comment by yrashk** [comment]
possibly, haven't decided yet.
