### ISSUE TITLE
Fails to install in mac ports environment

### ISSUE THREAD

**Issue by j2labs** [agner/agner#155]
It might be unique to my setup, I'm not sure.

Here is a gist with the output. I believe two errors are shown here.

https://gist.github.com/848057

**Comment by j2labs** [comment]
I get basically the same error when using oneliner (not oneliner.release).

Here is the output: https://gist.github.com/848060

**Comment by yrashk** [comment]
There was no /usr/local/bin

Now agner will ensure that AGNER_BIN (/usr/local/bin) is available
