### ISSUE TITLE
chicagoboss

### ISSUE THREAD

**Issue by evanmiller** [agner/agner#193]
Chicago Boss is a Rails-like web MVC for Erlang. I am requesting its inclusion on Agner. The spec file can be found here:

https://github.com/evanmiller/chicagoboss.agner

Project homepage:

http://www.chicagoboss.org/

**Comment by yrashk** [comment]
There was a mistake in the spec (git url contained your username), but I fixed this. Now chicagoboss has been packaged in agner main index and you're included in the chicagoboss team (so you can modify the spec at agner/chicagoboss.agner directly bypassing agner maintainers). Thanks!

**Comment by evanmiller** [comment]
great, thanks!
