### ISSUE TITLE
Tags in package description

### ISSUE THREAD

**Issue by eproxus** [agner/agner#21]
It would be nice to have a `{tags, [string()]}` field in the package description. Sometimes you want to have a nice textual `description` but still want the package to appear for certain keywords.

**Comment by yrashk** [comment]
I indeed though about either `tags` or `keywords` property — and I think I will be adding it — I just have to figure out what would be the best way to search through them. I have some ideas I'll try soon

**Comment by yrashk** [comment]
Ok, so I pushed out a first naïve implementation. You can now specify `{keywords,[string()]}` property and in order to be able to search using it, use this command line syntax:

```
 agner list -p keywords
```

It will append each entry that has keywords property with this text: `| keywords: [kwds]`

Hope this helps. Please let me know if that you want had in mind (more or less).

Thanks!

**Comment by eproxus** [comment]
That looks good! Will there be a `agner search` command as well? (That would automatically search both description and keywords?)

**Comment by yrashk** [comment]
My current suggestion is to do `list -d or -p keyword,anyotherproperty` and simply grep it.

**Comment by eproxus** [comment]
Hmm, seems cumbersome to me. Most package management systems have a `search` command (aptitude, gem, homebrew...).

**Comment by yrashk** [comment]
They do, I am just having a mental fight of simplicity vs. conformance with other package management systems (as `list ... | grep` pretty much covers search scenario). Let me think about it.

**Comment by yrashk** [comment]
Ok, so now you can use `agner search <TERM>` to search through packages. It is an alias form for `agner list --search <TERM>`

Hope this is what you were looking for.

**Comment by eproxus** [comment]
Yup, that looks spot on.

It's just that it's much more convenient typing a few characters that stretching for the pipe-key, most of the time.
