### ISSUE TITLE
erlando

### ISSUE THREAD

**Issue by yrashk** [agner/agner#210]
https://github.com/rabbitmq/erlando

**Comment by yrashk** [comment]
http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2011-April/012219.html

**Comment by JoeOsborn** [comment]
This https://github.com/JoeOsborn/erlando.agner ought to do it, if I understand agner correctly!

**Comment by yrashk** [comment]
Thanks!

**Comment by JoeOsborn** [comment]
Glad to help! Sorry for the lack of elegance in the spec, it seems I created as much work for you as I saved (:

**Comment by yrashk** [comment]
Not a problem, at least now you've got a better idea of how they are expected to be done for your next contribution :)

Thanks again!
