### ISSUE TITLE
curl agner fails

### ISSUE THREAD

**Issue by larshesel** [agner/agner#231]
Hi

I try to retrieve agner but it fails like below (it fails both for HEAD and for the latest release):

lhc@sonne:~$  curl https://github.com/agner/agner/raw/master/scripts/oneliner | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   295  100   295    0     0    163      0  0:00:01  0:00:01 --:--:--   340
Initialized empty Git repository in /tmp/agner.eH7jFB/.git/
remote: Counting objects: 1684, done.
remote: Compressing objects: 100% (981/981), done.
remote: Total 1684 (delta 1188), reused 980 (delta 697)
Receiving objects: 100% (1684/1684), 5.71 MiB | 660 KiB/s, done.
Resolving deltas: 100% (1188/1188), done.
Uncaught error in rebar_core: {'EXIT',
                                  {undef,
                                      [{crypto,start,[]},
                                       {rebar,run_aux,1},
                                       {rebar,main,1},
                                       {escript,run,2},
                                       {escript,start,1},
                                       {init,start_it,1},
                                       {init,start_em,1}]}}
make: **\* [deps] Error 1

I'm running on Ubuntu 10.10, with erlang R14B02 installed:

lhc@sonne:~$ which erl
/home/lhc/dev/erlang_install/otp-r14b02/bin/erl

Let me know if I can do anything to help resolve this issue.

Best regards,
Lars Hesel Christensen

**Comment by yrashk** [comment]
It looks like there's no crypto module, which is a part of standard
distribution. How exactly did you install Erlang?

**Comment by larshesel** [comment]
Hi, I installed erlang using 'kerl'. 

This install failed when it tried to retrieve 'agner'. I created an issue for this here: https://github.com/evax/kerl/issues/6.

Is it possible for me to check if I have the crypto module installed/enabled?

Best regards,
Lars

**Comment by yrashk** [comment]
Yes, start erl and do this: crypto:module_info().

On Mon, May 9, 2011 at 6:21 AM, larshesel
reply@reply.github.com
wrote:

**Comment by larshesel** [comment]
You are absolutely right: 

Eshell V5.8.3  (abort with ^G)
1> crypto:module_info().
*\* exception error: undefined function crypto:module_info/0

I will close this issue and fix my erlang installation. 

Thank you very much and sorry for the inconvenience.

Best regards,
Lars
