### ISSUE TITLE
erlang-stomp-client

### ISSUE THREAD

**Issue by nisbus** [agner/agner#236]
https://github.com/KodiEhf/erlang-stomp-client.agner

**Comment by yrashk** [comment]
Done as stomp_client

**Comment by nisbus** [comment]
Cool thanks, would you add a label to it as a package as well (I can't find where to do it or don't have permission to do so)?

**Comment by yrashk** [comment]
I am not sure what you mean?

**Comment by nisbus** [comment]
When I browse issues in the repo, some are labeled as packages or ideas etc.
I find it helpful when viewing the issues to see which are new packages and which are bug reports etc.
For some reason I cant see any way to add a label to my issue and so it has none.
Just a suggestion...

**Comment by yrashk** [comment]
Gotcha. Makes sense. Added a package label.

**Comment by nisbus** [comment]
Thanks :)
