### ISSUE TITLE
agner make fails, cannot find rebar git repo

### ISSUE THREAD

**Issue by larshesel** [agner/agner#245]
building the release version of agner fails when trying to get the rebar dependency:

.
.
.

[Processing dependency: rebar]
fatal: https://github.com/agner/rebar.git/info/refs not found: did you run git update-server-info on the server?

.
.
.

[Processing dependency: rebar]
fatal: https://github.com/agner/rebar.git/info/refs not found: did you run git update-server-info on the server?
[Building...]
ERROR: Build failed
[Processing dependency: typespecs]
[Building...]
==> typespecs (get-deps)
==> typespecs (compile)
cp: cannot stat `deps/rebar/ebin/rebar*': No such file or directory

to me it looks like it is trying to get rebar from the wong place. Should it not try to get it from http://github.com/basho/rebar.git ?

Anyway, retrieving rebar from basho/rebar works fine, but it still does not help me to install agner.

I'm installing agner on a ubuntu 11.4 natty narwhal computer.

Let me know if you need more information or if I can help in any other way.

Best regards,
Lars

**Comment by yrashk** [comment]
Just to verify, which command exactly do you run for this?

**Comment by yrashk** [comment]
Got it. Thanks for spotting this. Will push a fix in a few

**Comment by yrashk** [comment]
It was a mishap with merging rebar with an older version of @agner flavour I did yesterday. Should work now.

**Comment by larshesel** [comment]
Thanks for the quick fix. Something odd is happening now, though. It builds rebar, but seems to go into an infinite loop, and builds the stuff again and again:

[Building...]
make[8]: Entering directory `/tmp/agner.E5vrdd/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar'
==> rebar (get-deps)

.
.
.

[Building...]
make[9]: Entering directory `/tmp/agner.E5vrdd/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar/deps/rebar'
==> rebar (get-deps)
.
.
.

Should I open this as a new issue?

Best regards,
Lars

**Comment by yrashk** [comment]
hah, interesting. I'l just reopen this one.

**Comment by yrashk** [comment]
Broke too much stuff yesterday. Should be fine. Can you please try it again?

**Comment by larshesel** [comment]
If it's any help, I'm building the release version (stripped away the sudo stuff from the script as it will anyway install into my personal erlang installation):

DIR=`mktemp -u /tmp/agner.XXXXXX` &&
git clone https://github.com/agner/agner.git $DIR &&
cd $DIR && 
git checkout -b release origin/release &&
make && 
./agner install agner -v @release &&
echo Fetching index... && 
agner list -d | awk '{printf "."; fflush()}'  && echo &&  rm -rf $DIR

**Comment by larshesel** [comment]
trying again now.

**Comment by yrashk** [comment]
That was totally a bug I caused yesterday, I believe. Please check if my latest fix helped. I hope it did.

**Comment by larshesel** [comment]
Thanks a lot, it works beautifully now!
