### ISSUE TITLE
mochijson downloads all of mochiweb

### ISSUE THREAD

**Issue by aberman** [agner/agner#251]
It seems silly to list both mochijson and mochiweb when they are doing the same thing.  I was expecting mochijson to only download mochijson2 which would absolutely be my preference as I only need the JSON parser.  Is there any way to modify the agner file to only download the one file?

**Comment by yrashk** [comment]
mochijson's package build procedure removes all files that are not relevant to JSON parser (https://github.com/agner/mochijson.agner/blob/master/build.sh), so I don't see anything silly there.

Or did I misunderstand your question?

**Comment by aberman** [comment]
Yeah, that's fair that it only compiles the necessary files, but it actually downloads the entire mochiweb repository, so it just seems like a waste to do that.  But this is minor.

**Comment by yrashk** [comment]
Well, there's no way to clone a repo partially.
