### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by bhoflack** [agner/agner#255]
sh scripts/oneliner
Initialized empty Git repository in /private/tmp/agner.RVXf1U/.git/
remote: Counting objects: 1762, done.
remote: Compressing objects: 100% (594/594), done.
remote: Total 1762 (delta 1241), reused 1681 (delta 1162)
Receiving objects: 100% (1762/1762), 6.84 MiB | 642 KiB/s, done.
Resolving deltas: 100% (1241/1241), done.
==> agner.RVXf1U (get-deps)

=INFO REPORT==== 2-Jul-2011::10:54:26 ===
    application: gproc
    exited: {shutdown,{gproc_app,start,[normal,[]]}}
    type: temporary
ERROR: 'get-deps' failed while processing /private/tmp/agner.RVXf1U: {'EXIT',{badarg,[{ets,new,
                      [gproc,
                       [ordered_set,public,named_table,
                        {write_concurrency,true},
                        {read_concurrency,true}]]},
                 {gproc,create_tabs,0},
                 {gproc,start_link,0},
                 {agner,start,0},
                 {agner_rebar_plugin,'get-deps',2},
                 {rebar_core,run_modules,4},
                 {rebar_core,execute,4},
                 {rebar_core,process_dir,4}]}}
make: **\* [deps] Error 1

**Comment by yrashk** [comment]
What's the erlang version & OS?

**Comment by bhoflack** [comment]
Erlang R14A (erts-5.8)
Mac OS X 10.6.7

**Comment by yrashk** [comment]
Please try R14B+ as A is a "pre-release" version of Erlang not intended for production.

**Comment by bhoflack** [comment]
Thanks,  that fixed it.
