### ISSUE TITLE
Oneliner fails with R14B03

### ISSUE THREAD

**Issue by stepankuzmin** [agner/agner#264]
Gentoo Linux, Erlang R14B03.

==> agner.SRFbws (escriptize)
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{rebar_utils,expand_env_variable,
                                  ["method=classic","XDM_MANAGED",[]]},
                                 {rebar_port_compiler,merge_each_var,2},
                                 {rebar_port_compiler,setup_env,1},
                                 {rebar_core,'-setup_envs/2-lc$^0/1-0-',2},
                                 {rebar_core,'-setup_envs/2-lc$^0/1-0-',2},
                                 {rebar_core,setup_envs,2},
                                 {rebar_core,execute,4},
                                 {rebar_core,process_dir,4}]}}

**Comment by yrashk** [comment]
Should work now, please re-open if the issue persists.
