### ISSUE TITLE
Changing configuration

### ISSUE THREAD

**Issue by tsloughter** [agner/agner#265]
I am attempting to use agner (installed when kerl installs erlang) with dotcloud but the default configs will not work since I need everything to exist in my home directory.

$ agner config
prefix=/usr/local/agner
exact_prefix=/usr/local/agner/packages
bin=/usr/local/bin

My current work around has been to use fetch and compile myself and copy the libs to where they need to be. 

But where can I configure prefix and bin so that I can have agner install to my erlang install in my home directory? 

Thanks.

**Comment by yrashk** [comment]
https://github.com/agner/agner/blob/master/src/agner.erl#L13
AGNER_BIN & AGNER_PREFIX

**Comment by tsloughter** [comment]
Great, thanks!
