### ISSUE TITLE
Setting list of indices

### ISSUE THREAD

**Issue by tsloughter** [agner/agner#267]
The only way I can find to configure what indices for agner to use is by recompiling after editting the .app.erc file like:

{env,[{indices,[{github,"claimstrade"},{github,"agner"}]},

Which I would rather not have to recompile to add a index. Is there not a parameter or config file used by rebar to overwrite this value?

**Comment by yrashk** [comment]
there is, if you look into agner's readme (https://github.com/agner/agner#readme), you'll find this:

{agner_indices, [{github, "yourgithubusername"},{github,"agner"}].

**Comment by tsloughter** [comment]
I don't understand. That goes in the rebar.config file (like I put it in the .app file) and isn't that only used at compile time? So it isn't something used by the escript agner binary.

**Comment by yrashk** [comment]
yes, it's only for rebar based compilations

**Comment by yrashk** [comment]
You can use --indices option for the escript: agner --indices [{github,\"tsloughter\"}]

**Comment by tsloughter** [comment]
Thanks! I had been trying that before posting this issue and it wasn't working... I must have had some typo. Thanks again.

**Comment by tsloughter** [comment]
Ah, it was my version of agner on one machine. It returns --indices as an invalid option. While on my dotcloud instance it works fine. Thanks.
