### ISSUE TITLE
make failed on Ubuntu 10.04

### ISSUE THREAD

**Issue by phunehehe** [agner/agner#277]
I have tried both with Erlang package provided by Ubuntu and building Erlang from source. Below is the error message. Full output [here](http://pastebin.ca/2128015). I have seen some other issues that looks similar, but they are all closed.

Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{rebar_utils,get_deprecated_list,
                                  [{config,"/home/phunehehe/agner",
                                    [{require_otp_vsn,"R14|R15"},
                                     {lib_dirs,["deps"]},
                                     {escript_incl_apps,
                                      [getopt,gproc,rebar,plists,gen_fsm2,
                                       jsx]},
                                     {erl_opts,[{i,"deps"}]},
                                     {plugins,[agner_rebar_plugin]},
                                     local,
                                     {require_otp_vsn,"R14|R15"},
                                     {lib_dirs,["deps"]},
                                     {escript_incl_apps,
                                      [getopt,gproc,rebar,plists,gen_fsm2,
                                       jsx]},
                                     {erl_opts,[{i,"deps"}]},
                                     {plugins,[agner_rebar_plugin]}]},
                                   port_envs,port_env,[],"soon"],
                                  []},
                                 {rebar_port_compiler,port_env,1,[]},
                                 {rebar_port_compiler,setup_env,1,[]},
                                 {rebar_core,'-setup_envs/2-lc$^0/1-0-',2,[]},
                                 {rebar_core,'-setup_envs/2-lc$^0/1-0-',2,[]},
                                 {rebar_core,setup_envs,2,[]},
                                 {rebar_core,execute,4,[]},
                                 {rebar_core,process_dir,4,[]}]}}

**Comment by nuex** [comment]
Try updating the repo and making now. This looks like a duplicate of #278.

**Comment by phunehehe** [comment]
(closing since I'm not using this anymore, so can't reproduce)
