### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mcoolin** [agner/agner#278]
When doing this:
curl https://raw.github.com/agner/agner/master/scripts/oneliner | sh

I get:

Compiled src/agner_fetch.erl
Compiled src/agner_spec.erl
Compiled src/agner_server.erl
==> agner.Bb1NmX (escriptize)
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{rebar_utils,get_deprecated_list,
                                  [{config,"/tmp/agner.Bb1NmX",
                                    [{require_otp_vsn,"R14|R15"},
                                     {lib_dirs,["deps"]},
                                     {escript_incl_apps,
                                      [getopt,gproc,rebar,plists,gen_fsm2,
                                       jsx]},
                                     {erl_opts,[{i,"deps"}]},
                                     {plugins,[agner_rebar_plugin]},
                                     local,
                                     {require_otp_vsn,"R14|R15"},
                                     {lib_dirs,["deps"]},
                                     {escript_incl_apps,
                                      [getopt,gproc,rebar,plists,gen_fsm2,
                                       jsx]},
                                     {erl_opts,[{i,"deps"}]},
                                     {plugins,[agner_rebar_plugin]}]},
                                   port_envs,port_env,[],"soon"]},
                                 {rebar_port_compiler,port_env,1},
                                 {rebar_port_compiler,setup_env,1},
                                 {rebar_core,'-setup_envs/2-lc$^0/1-0-',2},
                                 {rebar_core,'-setup_envs/2-lc$^0/1-0-',2},
                                 {rebar_core,setup_envs,2},
                                 {rebar_core,execute,4},
                                 {rebar_core,process_dir,4}]}}
make: **\* [compile] Error 1

With 
Erlang R14B02 (erts-5.8.3) [source] [64-bit] [smp:2:2] [rq:2] [async-threads:0] [kernel-poll:false]

Eshell V5.8.3

**Comment by toland** [comment]
+1

I get the same issue on OS X with Erlang R15B01.

**Comment by tsloughter** [comment]
Same on Ubuntu with R15B01

**Comment by yrashk** [comment]
Fixed (#279)

**Comment by nuex** [comment]
I had to make a custom rebar.config file to pull the agner dependencies and compile. Then "cp agner rebar" to create the agnerized rebar that the agner build process depends on. Maybe this method needs to be rethought for future rebar releases looking forward.
