### ISSUE TITLE
encurses

### ISSUE THREAD

**Issue by odylbuild** [agner/agner#49]
{name, "encurses"}.
{authors, ["Jeff Zellner jeff.zellner@gmail.com"]}.
{description, "A NIF-based ncurses library for Erlang"}.
{homepage, "https://github.com/jzellner/encurses"}.
{rebar_compatible, true}.
{license, "Other"}.
{url, {git, "https://github.com/jzellner/encurses.git", {branch, "master"}}}.
{applications, []}.

**Comment by yrashk** [comment]
Done
