### ISSUE TITLE
smart_exceptions

### ISSUE THREAD

**Issue by yrashk** [agner/agner#89]
https://github.com/thomasl/smart_exceptions

should we?

**Comment by nox** [comment]
Maybe not. I remember reading about a smart_exceptions-related bug on erlang-questions and it wasn't pretty. Also the repository looks strange to me (why the fuck are stable and devel branches in the same branch?) and the tool itself is quite undocumented for such a big purpose.

**Comment by yrashk** [comment]
Agree, it might be a bad idea to include it at this moment
